# menu principale
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2

[[main]]
name = "Prezzi"
url = "/pricing"
weight = 3

[[main]]
name = "Contatti"
url = "/contact"
weight = 4

[[main]]
name = "FAQ"
url = "/faq"
weight = 5

# menu footer sinistro
[[footer_left]]
name = "Chi Siamo"
url = "#"

[[footer_left]]
name = "Guida Rapida"
url = "#"

[[footer_left]]
name = "Prezzi"
url = "/pricing"

# menu footer centrale
[[footer_middle]]
name = "Prezzi"
url = "/pricing"

[[footer_middle]]
name = "Piattaforma"
url = "#"

[[footer_middle]]
name = "Caratteristiche"
url = "#"

# menu footer destro
[[footer_right]]
name = "Privacy Policy"
url = "/privacy-policy"

[[footer_right]]
name = "Termini e Condizioni"
url = "/terms-conditions"

[[footer_right]]
name = "FAQ"
url = "/faq"
