backend:
  name: auth0
  domain: "dev-5w4hrn4vfetgy6pq.us.auth0.com"    # AUTH0_DOMAIN senza https://
  client_id: "TsPqh85zmMOUCsRREY63sT8nTApvIkeY"   # AUTH0_CLIENT_ID
  app_url: "https://electrafrigo.netlify.app/admin"  # URL admin del tuo sito

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/italian/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Immagine in evidenza", name: "image", widget: "image" }
      - { label: "Contenuto", name: "body", widget: "markdown" }
