backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/italian/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Immagine in evidenza", name: "image", widget: "image" }
      - { label: "Contenuto", name: "body", widget: "markdown" }

  - name: "volantini"
    label: "Volantini"
    folder: "content/italian/volantini"
    create: true
    slug: "{{year}}-{{month}}"
    fields:
      - label: "Titolo"
        name: "title"
        widget: "string"
      - label: "Data"
        name: "date"
        widget: "datetime"
      - label: "Volantino (PDF)"
        name: "file"
        widget: "file"
        media_folder: "/static/volantini"
        public_folder: "/volantini"
        allow_multiple: false
      - label: "Bozza"
        name: "draft"
        widget: "boolean"
        default: false


