name: Rinomina volantino PDF

on:
  push:
    paths:
      - 'static/uploads/*.pdf'

jobs:
  rename-volantino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rinomina PDF a volantino.pdf
        run: |
          cd static/uploads
          # Prendi il file PDF più recente che NON sia volantino.pdf
          newfile=$(ls -t *.pdf | grep -v volantino.pdf | head -n 1)
          if [ -n "$newfile" ]; then
            cp "$newfile" volantino.pdf
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add volantino.pdf
            git commit -m "Aggiornato volantino.pdf automaticamente"
            git push
          else
            echo "Nessun nuovo file PDF trovato"
          fi
